/*
 * Filter Coefficients (C Source) generated by the Filter Design and Analysis Tool
 *
 * Generated by MATLAB(R) 7.5 and the Signal Processing Toolbox 6.8.
 *
 * Generated on: 30-Jun-2010 17:25:51
 *
 */

/*
 * Discrete-Time IIR Filter (real)
 * -------------------------------
 * Filter Structure    : Direct-Form I, Second-Order Sections
 * Number of Sections  : 5
 * Stable              : Yes
 * Linear Phase        : No
 */

/* General type conversion for MATLAB generated C-code  */
#include "tmwtypes.h"
/*
 * Expected path to tmwtypes.h
 * F:\MATLAB\R2007b\extern\include\tmwtypes.h
 */
/*
 * Warning - Filter coefficients were truncated to fit specified data type.
 *   The resulting response may not match generated theoretical response.
 *   Use the Filter Design & Analysis Tool to design accurate
 *   single-precision filter coefficients.
 */
#define MWSPT_NSEC 11
const int NL[MWSPT_NSEC] = { 1,3,1,2,1,3,1,3,1,3,1 };
const real32_T NUM[MWSPT_NSEC][3] = {
  {
  0.0001033386579,              0,              0
  },
  {
                1,   -1.998498678,              1
  },
  {
                1,              0,              0
  },
  {
                1,              1,              0
  },
  {
  0.0007328730426,              0,              0
  },
  {
                1,   -1.999124527,              1
  },
  {
                1,              0,              0
  },
  {
                1,   -1.995633602,              1
  },
  {
    0.04924039915,              0,              0
  },
  {
                1,   -1.998993039,              1
  },
  {
      2592.070557,              0,              0
  }
};
const int DL[MWSPT_NSEC] = { 1,3,1,2,1,3,1,3,1,3,1 };
const real32_T DEN[MWSPT_NSEC][3] = {
  {
                1,              0,              0
  },
  {
                1,   -1.994302154,   0.9946861267
  },
  {
                1,              0,              0
  },
  {
                1,  -0.9945438504,              0
  },
  {
                1,              0,              0
  },
  {
                1,   -1.998684764,    0.999315083
  },
  {
                1,              0,              0
  },
  {
                1,   -1.990882158,   0.9910349846
  },
  {
                1,              0,              0
  },
  {
                1,   -1.996990085,   0.9975437522
  },
  {
                1,              0,              0
  }
};
